#!/bin/bash

echo "Please enter three-letter code of the day of the week"
echo "examples: Mon, Tue, ..., Sun"
read guess
echo "+++++++++++++++++"
x="$(date)"
day="${x:0:3}"

if [ "$guess" == "$day" ]
then
  echo "Good answer"
  echo "The day of the week is $day"
else
  echo "Bad answer"
  echo "Your answer: $guess, real day: $day"
fi
